<?php
/**
 * Functions to scour for homepage templates and build an array of them.
 * The array is then fed into options_framework settings for homepage layout
 * And that setting is fetched to display the proper homepage
 */

/**
 * Scans theme (and parent theme) for homepage templates.
 *
 * @return array An array of templates, with friendly names as keys and arrays with 'path' and 'thumb' as values
 */
if( !function_exists( 'get_homepage_templates' ) ) {

	function largo_get_home_templates() {

		$cache_key = 'largo_home_templates_' . get_option( 'stylesheet' );
		if ( false !== ( $home_templates = get_transient( $cache_key ) ) ) {
			return $home_templates;
		}

		$home_templates = array();
		$previous = false;
		foreach( array( 'template', 'stylesheet' ) as $option_name ) {

			$option_value = get_option( $option_name );

			// Skip second time if it's not a child theme
			if ( $option_value == $previous ) {
				break;
			}
			$previous = $option_value;

			$theme = wp_get_theme( $option_value );
			foreach( $theme->get_files( 'php', 1, true ) as $php_file ) {

				$name = $desc = '';
				$basename = str_replace( trailingslashit( $theme->get_stylesheet_directory() ), '', $php_file );
				$basename = str_replace( trailingslashit( $theme->get_template_directory() ), '', $basename );
				$template_data = file_get_contents( $php_file );
				if ( basename( $php_file ) !== basename( __FILE__ ) && preg_match( '|Home Template:(.*)$|mi', $template_data, $name ) ) {
					$name = _cleanup_header_comment( $name[1] );
					preg_match( '|Description:(.*)$|mi', $template_data, $desc);
					$home_templates[ trim( $name ) ] = array(
						'path' => $basename,	//eg 'homepages/my-homepage.php'
						'thumb' => largo_get_home_thumb( $theme, $basename ),
						'desc' => _cleanup_header_comment( $desc[1] )
					);
				}
			}

		}

		set_transient( $cache_key, $home_templates, HOUR_IN_SECONDS );

		return $home_templates;

	}
}

/**
 * Retrieves the thumbnail image for a homepage template, or a default
 *
 * @return string The public url of the image file to use for the given template's screenshot
 */
function largo_get_home_thumb( $theme, $file ) {
	$pngs = $theme->get_files( 'png', 1, true );
	$our_filename = basename( $file, '.php' ) . '.png';
	foreach ( (array)$pngs as $filename => $server_path ) {
		if ( basename($filename) == $our_filename ) {
			return str_replace( WP_CONTENT_DIR, content_url(), $server_path);
		}
	}

	//still here? Use a default
	return get_template_directory_uri() . '/homepages/no-thumb.png';
}

/**
 * Get the server path of the current homepage template
 *
 * @return string The full path to the PHP file of the current homepage template
 */
function largo_home_template_path() {
	$tpl = of_get_option( 'home_template', 'homepages/blog.php' );
	if ( ! $tpl ) return false;
	if ( file_exists( get_stylesheet_directory() . "/$tpl") ) {
		return get_stylesheet_directory() . "/$tpl";
	} else if ( file_exists( get_template_directory() . "/$tpl") ) {
		return get_template_directory() . "/$tpl";
	}
	return false;
}

/**
 * Register the sidebars specified in the Home Template
 */
function largo_register_home_sidebars() {
	$path = largo_home_template_path();
	$sidebar_string = '';
	$template_data = implode('', file( $path ));
	preg_match( '|Sidebars:(.*)$|mi', $template_data, $sidebar_string );
	if ( count( $sidebar_string ) > 1 ) {
		$sidebars = explode("|", _cleanup_header_comment($sidebar_string[1]));
		foreach ( $sidebars as $sidebar ) {
			preg_match( '|^(.*?)(\((.*)\))?$|', trim( $sidebar ), $sb );
			register_sidebar( array(
				'name' => trim($sb[1]),
				'id' => largo_make_slug( trim($sb[1]) ),
				'description' => (isset( $sb[3] ) ) ? trim($sb[3]) : __('Auto-generated by current homepage template'),
				'before_widget' => '<aside id="%1$s" class="%2$s clearfix">',
				'after_widget' 	=> "</aside>",
				'before_title' 	=> '<h3 class="widgettitle">',
				'after_title' 	=> '</h3>',
			) );
		}
	}

	// while we're at it, set the $largo['home_rail'] value
	global $largo;
	$rail = $largo['home_rail'] = TRUE;
	preg_match( '|Right Rail:(.*)$|mi', $template_data, $rail );
	if ( count($rail) > 1 ) {
		$rail_val = _cleanup_header_comment($rail[1]);
		if ( stripos($rail_val, 'hidden') !== FALSE || stripos($rail_val, 'none') !== FALSE ) {
			$largo['home_rail'] = FALSE;
		}
	}
}
add_action( 'widgets_init', 'largo_register_home_sidebars' );


/**
 * Enqueue scripts/styles
 */
function largo_enqueue_home_assets() {

	if ( is_admin() ) return;

	$path = largo_home_template_path();
	$pathinfo = pathinfo( $path );
	$template = of_get_option('home_template');
	//determine if child or parent
	if ( strpos( $pathinfo['dirname'] , get_stylesheet_directory() ) === FALSE ) {
		$uri = get_template_directory_uri() . "/";
	} else {
		$uri = get_stylesheet_directory_uri() . "/";
	}

	if ( is_file( str_replace(array('homepages/', '.php'), array('homepages/js/', '.js'), $path )) ) {
		wp_enqueue_script( 'largo-home-tpl-js',
			$uri . str_replace(array('homepages/', '.php'), array('homepages/js/', '.js'), $template ),
			array('jquery'),
			TRUE //in footer for now
		);
	}
	if ( is_file( str_replace(array('homepages/', '.php'), array('homepages/css/', '.css'), $path )) ) {
		wp_enqueue_style( 'largo-home-tpl-css',
			$uri . str_replace(array('homepages/', '.php'), array('homepages/css/', '.css'), $template )
		);
	}
}
add_action( 'wp_enqueue_scripts', 'largo_enqueue_home_assets' );


/**
 * Load custom template functions for the home templates
 */
function largo_load_custom_template_functions() {
	include_once __DIR__ . '/home-template-functions.php';
}